### ISSUE TITLE
Generacion de RFC mal en Version 2.0.1

### ISSUE THREAD

**Issue by tossedrichi** [josketres/rfc-facil#9]
Hola detecte una mala Generacion de RFC 

Generacion incorrecta de este RFC en Version 2.0.1 
![screenshot_20180124-183306](https://user-images.githubusercontent.com/22246830/35406002-fc491392-01c4-11e8-8788-6809b72437db.png)

Generacion Correcta en version 2.0.0
![screenshot_20180124-185025](https://user-images.githubusercontent.com/22246830/35406003-fc74e67a-01c4-11e8-9483-38952e945d18.png)

Solo me tope con este caso hasta ahora

**Comment by monchitos82** [comment]
Y lo puedes corregir facilmente. 
El bug está en el archivo:  `rfc-facil/src/main/java/com/josketres/rfcfacil/NaturalPersonTenDigitsCodeCalculator.java`

En la línea **119**, debería comparar con  `equals` en el statement para que no se omita _Marco_ por tener el substring _MA_

Así está:
```java
    private String filterName(String name) {

        String rawName = normalize(name).trim();
        if (rawName.contains(" ")) {
            if (rawName.startsWith("MA") || rawName.startsWith("MA.") || rawName.startsWith("MARIA") || rawName.startsWith("JOSE")) {
                return rawName.split(" ")[1];
            }
        }
        return name;
}
```

Así lo arreglas:

```java
    private String filterName(String name) {

        String rawName = normalize(name).trim();
        if (rawName.contains(" ")) {
            if (rawName.equals("MA") || rawName.startsWith("MA.") || rawName.startsWith("MARIA") || rawName.startsWith("JOSE")) {
                return rawName.split(" ")[1];
            }
        }
        return name;
}
```
